site_name: Jangkau AI Docs
site_url: https://docs.jangkau.ai

theme:
  name: material
  logo: assets/favicon.png       
  favicon: assets/favicon.png 
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: white
      accent: green
      toggle:
        icon: material/brightness-7
        name: Mode Gelap
    - media: "(prefers-color-scheme: dark)"
      primary: slate
      accent: green
      toggle:
        icon: material/brightness-4
        name: Mode Terang
  features:
    - navigation.expand 
    
extra_css:
  - stylesheets/extra.css

nav:
  - Selamat Datang di Jangkau AI: index.md
  - Mulai Di Sini: 
      - Pengenalan Jangkau AI: pengenalan.md
      - Registrasi dan Login: registrasi-dan-login.md
      - Reset Password: reset-password.md
      - Quick Start : start.md
  - Platform Terhubung : platform.md
  - Bot AI :
      - Informasi Umum : umum.md
      - Informasi Website : website.md
      - Jenis Bot : 
          - Booking/Reservasi : booking.md
          - Support Helpdesk : support.md
          - Lead Generation: 
              - Katalog Produk: lead-katalog.md
              - Pengaturan: lead-pengaturan.md
              - File: lead-file.md
              - QnA: lead-qna.md
              - Klasifikasi: lead-klasifikasi.md
              - Kategori: lead-kategori.md
              - Penomoran otomatis: lead-penomoran.md
          - Chat Commerce : chat.md
  - Agen : agen.md
  - Pembayaran : pembayaran.md