name: Sinkronisasi ke Bitbucket

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kode dari GitHub
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Dorong Kode ke Bitbucket
        run: |
          git remote add bitbucket https://${{ secrets.BITBUCKET_USERNAME }}:${{ secrets.BITBUCKET_PASSWORD }}@bitbucket.org/radyalabsdev/docs.jangkau.git
          git push bitbucket main --force